---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    application: keycloak
  name: keycloak
spec:
  host: keycloak-keycloak.apps.mycluster.mycluster.hhesham.com
  tls:
    termination: passthrough
  to:
    kind: Service
    name: keycloak
    weight: 100
