apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  clair:
    imagePullSecretName: redhat-pull-secret
    enabled: true
  quay:
    database:
      volumeSize: {{ .Values.dbsize | quote }} 
    enableRepoMirroring: true
    imagePullSecretName: redhat-pull-secret 
    envVars:
      - name: DEBUGLOG
        value: "true"
